### ISSUE TITLE
Add link to license in readme

### ISSUE THREAD

**Issue by darigovresearch** [jmschrei/torchegranate#1]
Thought it may be helpful/convenient to have a link to the license in the readme

**Comment by jmschrei** [comment]
Is this something that people normally do? The license is in the repo itself.

**Comment by darigovresearch** [comment]
@jmschrei yes this is a common thing to do, usually at the end of the readme.

Pull request https://github.com/jmschrei/torchegranate/pull/3 would resolve this issue.
