### ISSUE TITLE
FEATURE REQUEST - IndependentComponentsDistribution

### ISSUE THREAD

**Issue by liopeer** [jmschrei/torchegranate#4]
Hi, long-time user of pomegranate here. Thanks for the great work over the years!

My question: Is there any plan to bring the IndependentComponentsDistribution from pomegranate into torchegranate? I really liked the option of modeling each dimension of the emission with a specific distribution/mixture model. 

Of course if there's another way to do this in torchegranate that I'm just too dumb to realize, I'd also appreciate that info. :)

**Comment by jmschrei** [comment]
Added! https://github.com/jmschrei/torchegranate/blob/main/torchegranate/distributions/independent_components.py

This will be included in the next release, which should by the end of next week. You can pull the code and build it yourself by cloning the package and then using `python setup.py install` if you'd like it earlier than that.
