### ISSUE TITLE
Univariate Normal

### ISSUE THREAD

**Issue by balalofernandez** [jmschrei/torchegranate#6]
Is there a way to create a model using a univariate normal? I am forced to use at least 2 variables since:

```linalg.cholesky: The input tensor A must have at least 2 dimensions.```

in `normal.py`, l.139 `chol = torch.linalg.cholesky(self.covs)`

**Comment by jmschrei** [comment]
Pass `covariance_type='diag'` in when creating the object. I should auto-detect this case, though.
