### ISSUE TITLE
Commands not recognized after installing pomegranate/torchegranate

### ISSUE THREAD

**Issue by BootsManOut** [jmschrei/torchegranate#7]
Hi there,

I work in a pycharm environment, and I have installed pomegranate 1.0 and torchegranate 0.5.0, and tried it with both libraries.
After installing the library it does not recognize any of the commands.

For example running this code:
```
from pomegranate import *

test = State(DiscreteDistribution({
    "good": 0.7,
    "bad": 0.2,
    "medium": 0.1
}), name="test")
```

returns the error:

> NameError: name 'State' is not defined

The same happens when I replace pomegranate with torchegranate.

I use python 3.10.

Why could this be happening?

**Comment by jmschrei** [comment]
pomegranate v1.0.0 is not back-compatible with previous versions: `State` objects have been removed and `DiscreteDistribution` is now `Categorical`. Please read the README and see the latest tutorials.
